# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: about everything
email: w732qq@gmail.com
url: site.github.url

# Build settings
markdown: kramdown

timezone: Europe/Moscow

defaults:
  -
    scope:
      path: ''
    values:
      layout: default
